-- CreateEnum
CREATE TYPE "FeeCategory" AS ENUM ('PARENT_SUPPORT', 'TUITION_FEE', 'DEPOSIT_FEE', 'ELECTRICITY_TRANSPORT', 'LIBRARY_FEE', 'REGISTRATION_FEE', 'IDENTITY_SPORTS', 'EXAM_FEE_1', 'EXAM_FEE_2', 'EXAM_FEE_3', 'SEE_EXAM_FEE', 'BUILDING_MISC_FEE', 'CERTIFICATE_FEE', 'GRADE_SHEET', 'TIE_BELT');

-- AlterTable
ALTER TABLE "Fee" ADD COLUMN     "category" "FeeCategory" NOT NULL DEFAULT 'TUITION_FEE';
